Feature/test with rspec
MrSayyod/Tic-Tac-Toe-game pull request #7
Opened 2020-05-13 09:15 UTC by Hermela-Fikre

- Used existed repositories for tic tac toe.
- Each method was tested with the describe block.
- Used one it block for each expected behaviour.
- Fixed linter errors.

2020-05-13 17:28 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @Hermela-Fikre @MrSayyod 

Nice introduction to the milestone.
However, there are some changes to do

1. When using RSpec, the file containing test must finish by `_spec.rb`

2. When running the test I got this error
```rb
$ rspec spec/test.rb 

An error occurred while loading ./spec/test.rb.
Failure/Error: require '../lib/game.rb'

LoadError:
  cannot load such file -- ../lib/game.rb
# ./spec/test.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00002 seconds (files took 0.13248 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```
3. Please, read the comments left below.

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-05-13 17:28 UTC, maelfosso commented on spec/test.rb
> +  end
Check the content of the `game.board` at that position

2020-05-13 17:28 UTC, maelfosso commented on spec/test.rb
> +  end
Check also what happens when a value is set at a position

2020-05-13 17:28 UTC, maelfosso commented on spec/test.rb
> +  end
There is also a case that takes us to `False`.

2020-05-13 17:28 UTC, maelfosso commented on spec/test.rb
> +  end
The method `valid_letter` doesn't always return `True`. What about the other case?

2020-05-13 17:28 UTC, maelfosso commented on spec/test.rb
> +  end
What about the `False` situation?

2020-05-14 08:14 UTC, MrSayyod commented on spec/test.rb
> +  end
Fixed

2020-05-14 08:15 UTC, MrSayyod commented on spec/test.rb
> +  end
fixed

2020-05-14 08:15 UTC, MrSayyod commented on spec/test.rb
> +  end
fixed

2020-05-16 01:15 UTC, rOluochKe approved these changes
Hello @MrSayyod and @Hermela-Fikre 
### You have done really well in this project and for also implementing changes from the previous reviews :clap: The project looks good and congratulations :boom: :100: it has been approved.
### You can merge and submit a project completion form from the dashboard. Good luck with the next project.
- Happy coding!

2020-05-16 01:43 UTC, merged